### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by chasedeanda** [jledentu/vue-finder#124]
It'd be great if there were breadcrumbs included or if there was an event for when an item was clicked on so we can add them ourselves. Is there anyway to get the current active items?

**Comment by jledentu** [comment]
I prefer to not add too much UI in this library in order to make it lightweight, but you can add it relatively simply by using the `expanded` event:

```js
expanded(expandedItems, sourceEvent) {
  // expandedItems contains the list of IDs of expanded items: parent > child > ... > leaf
}
```

The event payload contains a list of IDs rather than full objects, I guess I could improve that.

**Comment by chasedeanda** [comment]
Thank you for your response! Yeah this solution worked out well. Returning the full object would be much easier to work with so we don't have to walk the tree to find the correct node just to display its name.
