### ISSUE TITLE
Selecting parent could select the children too

### ISSUE THREAD

**Issue by byteofprash** [jledentu/vue-finder#128]
Firstly, thanks for this wonderful component. 
I come from systems programming world, so quite new to this JS world. 

Is there a way to auto "select" the children when a parent node is "selected"?
I also found that we get the id of the node when it's selected. Is there a way to get the children of this item recursively in way so I can change the selected parameter?

Thanks.

**Comment by jledentu** [comment]
Hi @byteofprash, thanks for your comment! 

There is currently no way to select all children directly. It's up to you to find the children of the selected parent from the parent ID. But I think I will make a change that adds a `selectedItems` property in the `select` event:

```js
onSelect({ selected, selectedItems }) {
  console.log(
    `Items with ${selected.join()} IDs are now selected`
  );

  console.log(
    `Items with ${selectedItems.map(item => item.id).join()} IDs are now selected`
  );
}
```
I think I'll do that this week.

A prop `autoSelectChildren` could be possible too. Will think about it.
