### ISSUE TITLE
Needs more documentation

### ISSUE THREAD

**Issue by travis-bear** [jledentu/vue-finder#129]
The README/front page should have this info, or a link to it

- What are the parameters?
- How is the tree data set?
- What are the stylable classes?
- An interactive example, possibly a code pen

People need this to be able to quickly evaluate if this component meets their needs

**Comment by jledentu** [comment]
Hi. https://vue-finder.netlify.app actually contains some documentation:

* [Interactive examples](https://vue-finder.netlify.app/examples.html)
* [Props](https://vue-finder.netlify.app/api.html#props)
* [Customization](https://vue-finder.netlify.app/customization.html#css-classes)

Maybe you didn't see the link to the website? Do you think I should put all documentation in the README?

**Comment by travis-bear** [comment]
That link is great.  I think it's fine either way if you put the documentation directly in the README or not.  If not, it would be helpful to link to it directly from the README, with clear text indicating this is the documentation.
