### ISSUE TITLE
Bad link to demo

### ISSUE THREAD

**Issue by knightq** [jledentu/vue-finder#138]
in the `README.md` the link on statement:

> The documentation is available on the [website](https://vue-treeselect.js.org/).

points to [https://vue-treeselect.js.org/](https://vue-treeselect.js.org/) instead of [https://vue-finder.netlify.app/getting-started.html#installation](https://vue-finder.netlify.app/getting-started.html#installation).

**Comment by jledentu** [comment]
OMG! vue-treeselect is a library I use a lot, and I love their clear documentation that I took as inspiration (among other docs like https://vue-select.org/ or https://www.njleonzhang.com/vue-data-tables/#/en-us). Apparently I copied/pasted the wrong link when I improved the README recently.

Let's fix that. Thanks @knightq!

**Comment by jledentu** [comment]
Closed by #139
