### ISSUE TITLE
@Selected Event not working (Vue 3)

### ISSUE THREAD

**Issue by ProNotion** [jledentu/vue-finder#190]
Using the latest pre-release with support for v3 the @selected event does not seem to work at all.

**Comment by ProNotion** [comment]
I'm not sure if I misunderstood the purpose of the event. I do not have checkboxes enabled but I need to handle the clicking of a leaf node. When I say "selected" though I don't mean checking a checkbox I mean that it has been clicked in the UI. So, without wasting your time it may be a misinterpretation of the docs and this event?

**Comment by jledentu** [comment]
@ProNotion Ok, I checked that everything works as expected.

- `select` event (not `selected`) is emitted when an node is selected by checking a checkbox. This event is relevant only when the `selectable` prop is `true`.
- `expand` is emitted when a node is expanded. **It's also emitted on leaf nodes**. Even though leaf nodes do not typically "expand" in the same way that other nodes do (that's what may have caused you confusion), the component emits the same expand event for consistency.

So use the `expand` event. The payload contains 2 properties:
- `expanded`, the list of "expanded" nodes. The leaf will be the last item of the array.
- `sourceEvent`, the type of event that triggered the expand action (a such action can be triggered by a click, a focus from keyboard navigation, drag & drop...)

**Comment by ProNotion** [comment]
In case it is of use to anyone else here is my solution...

```
onTreeExpand({expanded, sourceEvent}) {
      if (sourceEvent === "click") {
        let node = this.findDocument(this.tree, expanded[expanded.length - 1])
        if(node.isLeaf){
          window.open("/docs/" + node.path + "/" + node.label);
        }
      }
    },
    findDocument(obj, id) {
      let result = null;
      const recursiveSearch = (obj = {}) => {
        if (!obj || typeof obj !== 'object') {
          return;
        }
        if (obj["id"] === id) {
          result = obj;
        }
        Object.keys(obj).forEach(function (k) {
          recursiveSearch(obj[k]);
        });
      }; recursiveSearch(obj)
      
      return result;
    }
```

I'm open to opinions on how this might be approved.

**Comment by jledentu** [comment]
@ProNotion Ok, I see what's your problem.

In my own app, I build the original tree from a list (using https://github.com/philipstanislaus/performant-array-to-tree), so on click I can find the clicked node in the list. I could also maintain a `Map` listing nodes by their IDs. Maybe we could use a similar strategy (keeping a `Map` with nodes references).

But it would be better if the library itself passed the clicked node data in the event. I'll get a look into this.

**Comment by jledentu** [comment]
I see 2 options:

- Add another parameter in the `expand` event: `sourceNode` that would be the node that triggered the event (the focused, dragged or clicked item)
- Emit other specialized events: `click`, `focus` with the source node data as payload

The 2nd option seems more understandable and explicit, maybe? Would avoid confusion about the `expand` event...

**Comment by ProNotion** [comment]
> @ProNotion Ok, I see what's your problem.
> 
> In my own app, I build the original tree from a list (using https://github.com/philipstanislaus/performant-array-to-tree), so on click I can find the clicked node in the list. I could also maintain a `Map` listing nodes by their IDs. Maybe we could use a similar strategy (keeping a `Map` with nodes references).
> 

Looks interesting, so you start out with a flattened array of nodes then convert it to the tree, presumably using the array for the lookups?

> But it would be better if the library itself passed the clicked node data in the event. I'll get a look into this.

I definitely agree with this as it would solve my use case.

> The 2nd option seems more understandable and explicit, maybe? Would avoid confusion about the expand event...

Where would the confusion come from? I can see it being useful in both scenarios to have access to the node that was clicked and not just the id of the item which then requires further work to retrieve the full node.

**Comment by jledentu** [comment]
Hi @ProNotion, the latest 3.1.0 pre-release adds a new `expandedItems` property in `expand` payload:

```js
onExpand({ expanded, sourceEvent, expandedItems }) {
  console.log(
    `Items with ${expanded.join()} IDs are now expanded`
  );
}
```

This will allow to retrieve more easily data of expanded items.

**Comment by jledentu** [comment]
I close this issue since I think it's solved by latest versions.
