### ISSUE TITLE
Improvement: Add the new index to the 'moved' event

### ISSUE THREAD

**Issue by tomcoonen** [jledentu/vue-finder#79]
It would be nice to have the new item index available on the `moved` event so you can handle the change from there.

**Comment by jledentu** [comment]
I made a PR to add a `index` property, which is the index of the dropzone where the item is dragged. When dragged on an item, the index is `undefined` (the element is pushed at the end of the children). Please note that this index is not the displayed position of the item if a `sortBy` is applied.

**Comment by tomcoonen** [comment]
Great work :)
